from httpx import AsyncClient
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from src.posts.constants import PostStatus
from src.posts.models import Post


async def test_criar_um_post_devolve_201_e_grava_no_banco(
    client: AsyncClient, session: AsyncSession
) -> None:
    response = await client.post("/posts", json={"title": "First", "body": "Body"})

    assert response.status_code == 201
    assert response.json()["status"] == PostStatus.DRAFT

    rows = await session.execute(select(Post))
    gravados = rows.scalars().all()
    assert [p.title for p in gravados] == ["First"]


async def test_o_contrato_de_saida_nao_devolve_campo_alem_do_declarado(
    client: AsyncClient,
) -> None:
    response = await client.post("/posts", json={"title": "First", "body": "Body"})

    assert set(response.json()) == {
        "id",
        "title",
        "body",
        "status",
        "created_at",
        "published_at",
    }


async def test_campo_desconhecido_na_entrada_e_recusado(client: AsyncClient) -> None:
    response = await client.post(
        "/posts", json={"title": "First", "body": "Body", "status": "published"}
    )

    assert response.status_code == 422


async def test_buscar_post_inexistente_devolve_404_da_taxonomia(client: AsyncClient) -> None:
    response = await client.get("/posts/404")

    assert response.status_code == 404
    assert response.json()["code"] == "post_not_found"


async def test_publicar_duas_vezes_devolve_409(client: AsyncClient) -> None:
    criado = await client.post("/posts", json={"title": "First", "body": "Body"})
    post_id = criado.json()["id"]

    primeira = await client.post(f"/posts/{post_id}/publish")
    segunda = await client.post(f"/posts/{post_id}/publish")

    assert primeira.status_code == 200
    assert segunda.status_code == 409
    assert segunda.json()["code"] == "post_already_published"


async def test_limite_de_pagina_acima_do_teto_e_recusado(client: AsyncClient) -> None:
    response = await client.get("/posts", params={"limit": 1000})

    assert response.status_code == 422


async def test_a_rota_sincrona_de_relatorio_responde_texto(client: AsyncClient) -> None:
    response = await client.get("/reports/posts.csv")

    assert response.status_code == 200
    assert response.text.startswith("# generated by harness")


async def test_a_rota_assincrona_serializa_o_que_esta_no_banco(client: AsyncClient) -> None:
    await client.post("/posts", json={"title": "First", "body": "Body"})

    response = await client.get("/reports/posts-live.csv")

    assert response.status_code == 200
    assert "First" in response.text
