from typing import Annotated

from fastapi import APIRouter, Depends
from fastapi.responses import PlainTextResponse
from starlette.concurrency import run_in_threadpool

from src.posts.dependencies import PaginationDep, ServiceDep
from src.reports.service import render_posts_csv

router = APIRouter(prefix="/reports", tags=["reports"])


def format_header(generated_by: str = "harness") -> str:
    return f"# generated by {generated_by}"


HeaderDep = Annotated[str, Depends(format_header)]


@router.get("/posts.csv", response_class=PlainTextResponse)
def posts_csv(header: HeaderDep) -> str:
    """Rota `def`: a FastAPI a executa no threadpool.

    Motivo: o corpo é totalmente bloqueante. Declarada `def`, ela sai do laço
    de eventos e deixa as rotas assíncronas seguirem atendendo.
    """
    return f"{header}\nid,title,status\n"


@router.get("/posts-live.csv", response_class=PlainTextResponse)
async def posts_live_csv(service: ServiceDep, pagination: PaginationDep) -> str:
    """Rota `async def` que precisa de uma chamada bloqueante no meio.

    Motivo: a leitura do banco é aguardável e a serialização não. `run_in_threadpool`
    é o que impede a parte bloqueante de travar o laço enquanto ela roda.
    """
    limit, offset = pagination
    posts = await service.list(limit=limit, offset=offset)
    return await run_in_threadpool(render_posts_csv, posts)
