ALTER TABLE categories ADD COLUMN label TEXT NOT NULL DEFAULT '';
ALTER TABLE categories ADD COLUMN is_system INTEGER NOT NULL DEFAULT 1;
UPDATE categories SET label = 'Hospedagem' WHERE name = 'Accomodation';
UPDATE categories SET label = 'Tarifa de conta' WHERE name = 'Account fees';
UPDATE categories SET label = 'Passagem aérea' WHERE name = 'Airport and airlines';
UPDATE categories SET label = 'Automóvel' WHERE name = 'Automotive';
UPDATE categories SET label = 'Tarifa bancária' WHERE name = 'Bank fees';
UPDATE categories SET label = 'Bicicleta' WHERE name = 'Bicycle';
UPDATE categories SET label = 'Livraria' WHERE name = 'Bookstore';
UPDATE categories SET label = 'Cashback' WHERE name = 'Cashback';
UPDATE categories SET label = 'Cinema e shows' WHERE name = 'Cinema, theater and concerts';
UPDATE categories SET label = 'Roupas' WHERE name = 'Clothing';
UPDATE categories SET label = 'Tarifa de cartão' WHERE name = 'Credit card fees';
UPDATE categories SET label = 'Pagamento de cartão' WHERE name = 'Credit card payment';
UPDATE categories SET label = 'Dentista' WHERE name = 'Dentist';
UPDATE categories SET label = 'Serviços digitais' WHERE name = 'Digital services';
UPDATE categories SET label = 'Doações' WHERE name = 'Donations';
UPDATE categories SET label = 'Comer fora' WHERE name = 'Eating out';
UPDATE categories SET label = 'Ensino' WHERE name = 'Education';
UPDATE categories SET label = 'Educação' WHERE name = 'Educação';
UPDATE categories SET label = 'Energia elétrica' WHERE name = 'Electricity';
UPDATE categories SET label = 'Eletrônicos' WHERE name = 'Electronics';
UPDATE categories SET label = 'Delivery de comida' WHERE name = 'Food delivery';
UPDATE categories SET label = 'Apostas' WHERE name = 'Gambling';
UPDATE categories SET label = 'Posto de combustível' WHERE name = 'Gas stations';
UPDATE categories SET label = 'Supermercado' WHERE name = 'Groceries';
UPDATE categories SET label = 'Plano de saúde' WHERE name = 'Healthcare';
UPDATE categories SET label = 'Clínicas e exames' WHERE name = 'Hospital clinics and labs';
UPDATE categories SET label = 'Utensílios de casa' WHERE name = 'Houseware';
UPDATE categories SET label = 'Casa' WHERE name = 'Housing';
UPDATE categories SET label = 'Receita' WHERE name = 'Income';
UPDATE categories SET label = 'Imposto de renda' WHERE name = 'Income taxes';
UPDATE categories SET label = 'Seguro' WHERE name = 'Insurance';
UPDATE categories SET label = 'Juros cobrados' WHERE name = 'Interests charged';
UPDATE categories SET label = 'Internet' WHERE name = 'Internet';
UPDATE categories SET label = 'Investimentos' WHERE name = 'Investments';
UPDATE categories SET label = 'Crianças e brinquedos' WHERE name = 'Kids and toys';
UPDATE categories SET label = 'Multa e cheque especial' WHERE name = 'Late payment and overdraft costs';
UPDATE categories SET label = 'Lazer' WHERE name = 'Leisure';
UPDATE categories SET label = 'Empréstimo' WHERE name = 'Loans and financing';
UPDATE categories SET label = 'Receita não recorrente' WHERE name = 'Non-recurring income';
UPDATE categories SET label = 'Sem categoria' WHERE name = 'Não classificado';
UPDATE categories SET label = 'Material de escritório' WHERE name = 'Office supplies';
UPDATE categories SET label = 'Cursos online' WHERE name = 'Online Courses';
UPDATE categories SET label = 'Compra online' WHERE name = 'Online shopping';
UPDATE categories SET label = 'Óculos e lentes' WHERE name = 'Optometry';
UPDATE categories SET label = 'Estacionamento' WHERE name = 'Parking';
UPDATE categories SET label = 'Pet e veterinário' WHERE name = 'Pet supplies and vet';
UPDATE categories SET label = 'Farmácia' WHERE name = 'Pharmacy';
UPDATE categories SET label = 'Juros e dividendos' WHERE name = 'Proceeds interests and dividends';
UPDATE categories SET label = 'Ônibus e metrô' WHERE name = 'Public transportation';
UPDATE categories SET label = 'Financiamento imobiliário' WHERE name = 'Real estate financing';
UPDATE categories SET label = 'Salário' WHERE name = 'Salary';
UPDATE categories SET label = 'Transferência própria' WHERE name = 'Same person transfer';
UPDATE categories SET label = 'Transferência própria em dinheiro' WHERE name = 'Same person transfer - CASH';
UPDATE categories SET label = 'Escola' WHERE name = 'School';
UPDATE categories SET label = 'Serviços' WHERE name = 'Services';
UPDATE categories SET label = 'Compras' WHERE name = 'Shopping';
UPDATE categories SET label = 'Artigos esportivos' WHERE name = 'Sports goods';
UPDATE categories SET label = 'IOF' WHERE name = 'Tax on financial operations';
UPDATE categories SET label = 'Táxi e aplicativo' WHERE name = 'Taxi and ride-hailing';
UPDATE categories SET label = 'Telefonia' WHERE name = 'Telecom';
UPDATE categories SET label = 'Telecomunicações' WHERE name = 'Telecommunications';
UPDATE categories SET label = 'Pix para terceiro' WHERE name = 'Third party transfer - PIX';
UPDATE categories SET label = 'Ingressos' WHERE name = 'Tickets';
UPDATE categories SET label = 'Pedágio' WHERE name = 'Tolls and in vehicle payment';
UPDATE categories SET label = 'Multa de trânsito' WHERE name = 'Traffic tickets';
UPDATE categories SET label = 'Boleto' WHERE name = 'Transfer - Bank Slip';
UPDATE categories SET label = 'Saque e depósito' WHERE name = 'Transfer - Cash';
UPDATE categories SET label = 'Transferência interna' WHERE name = 'Transfer - Internal';
UPDATE categories SET label = 'Pix' WHERE name = 'Transfer - PIX';
UPDATE categories SET label = 'TED' WHERE name = 'Transfer - TED';
UPDATE categories SET label = 'Transferência' WHERE name = 'Transfers';
UPDATE categories SET label = 'Viagem' WHERE name = 'Travel';
UPDATE categories SET label = 'Faculdade' WHERE name = 'University';
UPDATE categories SET label = 'Manutenção do veículo' WHERE name = 'Vehicle maintenance';
UPDATE categories SET label = 'IPVA e licenciamento' WHERE name = 'Vehicle ownership taxes and fees';
UPDATE categories SET label = 'Água' WHERE name = 'Water';
UPDATE categories SET label = 'Academia e bem-estar' WHERE name = 'Wellness and fitness';
UPDATE categories SET label = name WHERE label = '';
